# Generated by Django 5.0.2 on 2024-03-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='likes',
        ),
    ]
