# Generated by Django 5.0 on 2024-04-11 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_interests_description_interests_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscriptions_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
