# Generated by Django 5.0.2 on 2024-03-13 16:41

import django
from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_network_app', '0002_reposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reposts',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'id__in': [12, 14]}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
