# Generated by Django 5.0.2 on 2024-03-14 16:08

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0003_alter_reposts_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
