# Generated by Django 5.0.2 on 2024-03-14 17:14

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0005_remove_publications_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images'),
        ),
    ]
