    # Generated by Django 5.0.2 on 2024-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
