# Generated by Django 5.0.2 on 2024-03-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socnetapp', '0004_remove_publications_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
